apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: project
spec:
  replicas: 10
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project-container
          image: amckee457/project:latest
          ports:
            - containerPort: 8080       
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  type: ClusterIP
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080